import { Document, Image, Link, Page, StyleSheet, Text, View } from "@react-pdf/renderer";

import type { ProposalRenderModel } from "@/lib/proposals/proposal-render-service";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#111827",
    lineHeight: 1.45,
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 40,
    right: 40,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 8,
    color: "#6b7280",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  companyName: {
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    marginBottom: 4,
  },
  logo: {
    width: 120,
    height: 40,
    objectFit: "contain",
    marginBottom: 8,
  },
  muted: {
    color: "#6b7280",
    fontSize: 9,
  },
  proposalMeta: {
    textAlign: "right",
  },
  sectionTitle: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    marginBottom: 6,
    marginTop: 14,
    color: "#111827",
  },
  paragraph: {
    marginBottom: 8,
    whiteSpace: "pre-wrap",
  },
  twoColumn: {
    flexDirection: "row",
    gap: 20,
    marginBottom: 12,
  },
  column: {
    flex: 1,
  },
  pricingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 3,
  },
  pricingTotal: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 8,
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    fontFamily: "Helvetica-Bold",
    fontSize: 12,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f3f4f6",
    padding: 6,
    fontFamily: "Helvetica-Bold",
    fontSize: 8,
  },
  tableRow: {
    flexDirection: "row",
    padding: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
    fontSize: 8,
  },
  colDesc: { width: "46%" },
  colQty: { width: "12%", textAlign: "right" },
  colUnit: { width: "12%" },
  colCost: { width: "15%", textAlign: "right" },
  colTotal: { width: "15%", textAlign: "right" },
  signatureRow: {
    flexDirection: "row",
    gap: 24,
    marginTop: 24,
  },
  signatureBlock: {
    flex: 1,
    borderTopWidth: 1,
    borderTopColor: "#9ca3af",
    paddingTop: 8,
    minHeight: 60,
  },
  signatureImage: {
    width: 180,
    height: 48,
    objectFit: "contain",
    marginBottom: 6,
  },
  photoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 8,
  },
  photo: {
    width: "48%",
    height: 120,
    objectFit: "cover",
    borderRadius: 4,
  },
  attachmentRow: {
    marginBottom: 4,
  },
});

type ProposalPdfDocumentProps = {
  model: ProposalRenderModel;
};

function Section({ title, body }: { title: string; body: string }) {
  return (
    <View>
      <Text style={styles.sectionTitle}>{title}</Text>
      <Text style={styles.paragraph}>{body}</Text>
    </View>
  );
}

function LineItemTable({
  title,
  rows,
}: {
  title: string;
  rows: ProposalRenderModel["lineItemTables"][number]["rows"];
}) {
  if (!rows.length) {
    return null;
  }

  return (
    <View wrap={false}>
      <Text style={styles.sectionTitle}>{title}</Text>
      <View style={styles.tableHeader}>
        <Text style={styles.colDesc}>Description</Text>
        <Text style={styles.colQty}>Qty</Text>
        <Text style={styles.colUnit}>Unit</Text>
        <Text style={styles.colCost}>Unit Cost</Text>
        <Text style={styles.colTotal}>Total</Text>
      </View>
      {rows.map((row, index) => (
        <View key={`${row.description}-${index}`} style={styles.tableRow} wrap={false}>
          <Text style={styles.colDesc}>{row.description}</Text>
          <Text style={styles.colQty}>{row.quantity}</Text>
          <Text style={styles.colUnit}>{row.unit}</Text>
          <Text style={styles.colCost}>{row.unitCost}</Text>
          <Text style={styles.colTotal}>{row.total}</Text>
        </View>
      ))}
    </View>
  );
}

function PageFooter({ proposalNumber }: { proposalNumber: string }) {
  return (
    <View style={styles.footer} fixed>
      <Text>Generated by VoltPilot</Text>
      <Text>{proposalNumber}</Text>
    </View>
  );
}

export function ProposalPdfDocument({ model }: ProposalPdfDocumentProps) {
  const scopeSection = model.textSections.find((section) => section.id === "scope");
  const detailSections = model.textSections.filter((section) => section.id !== "scope");
  const summarySections = detailSections.filter((section) =>
    ["materials", "labor", "equipment"].includes(section.id)
  );
  const legalSections = detailSections.filter(
    (section) => !["materials", "labor", "equipment"].includes(section.id)
  );

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <View>
            {model.branding.companyLogoUrl ? (
              // eslint-disable-next-line jsx-a11y/alt-text -- react-pdf Image
              <Image src={model.branding.companyLogoUrl} style={styles.logo} />
            ) : null}
            <Text style={styles.companyName}>{model.branding.companyName}</Text>
            {model.branding.addressLines.map((line) => (
              <Text key={line} style={styles.muted}>
                {line}
              </Text>
            ))}
            {model.branding.phone ? <Text style={styles.muted}>{model.branding.phone}</Text> : null}
            {model.branding.email ? <Text style={styles.muted}>{model.branding.email}</Text> : null}
            {model.branding.licenseNumber ? (
              <Text style={styles.muted}>License: {model.branding.licenseNumber}</Text>
            ) : null}
          </View>
          <View style={styles.proposalMeta}>
            <Text style={{ fontFamily: "Helvetica-Bold", fontSize: 14 }}>PROPOSAL</Text>
            <Text>{model.meta.proposalNumber ?? "—"}</Text>
            <Text>{model.meta.proposalDateLabel}</Text>
            {model.meta.expirationDateLabel ? (
              <Text style={styles.muted}>Expires {model.meta.expirationDateLabel}</Text>
            ) : null}
            <Text style={{ marginTop: 6, fontFamily: "Helvetica-Bold" }}>
              {model.meta.amountLabel}
            </Text>
          </View>
        </View>

        <View style={styles.twoColumn}>
          <View style={styles.column}>
            <Text style={styles.sectionTitle}>Customer</Text>
            <Text>{model.customer.companyName}</Text>
            <Text style={styles.muted}>{model.customer.contactName}</Text>
            <Text style={styles.muted}>{model.customer.email}</Text>
            {model.customer.phone ? (
              <Text style={styles.muted}>{model.customer.phone}</Text>
            ) : null}
          </View>
          <View style={styles.column}>
            <Text style={styles.sectionTitle}>Project</Text>
            <Text>{model.project.name}</Text>
            {model.project.address ? (
              <Text style={styles.muted}>{model.project.address}</Text>
            ) : null}
            {model.project.generalContractor ? (
              <Text style={styles.muted}>GC: {model.project.generalContractor}</Text>
            ) : null}
            <Text style={styles.muted}>Type: {model.project.type}</Text>
          </View>
        </View>

        {scopeSection ? <Section title={scopeSection.title} body={scopeSection.body} /> : null}

        {summarySections.map((section) => (
          <Section key={section.id} title={section.title} body={section.body} />
        ))}

        {model.pricingSummary ? (
          <View>
            <Text style={styles.sectionTitle}>Estimate Summary</Text>
            {model.pricingSummary.map((row) =>
              row.emphasized ? (
                <View key={row.label} style={styles.pricingTotal}>
                  <Text>{row.label}</Text>
                  <Text>{row.value}</Text>
                </View>
              ) : (
                <View key={row.label} style={styles.pricingRow}>
                  <Text>{row.label}</Text>
                  <Text>{row.value}</Text>
                </View>
              )
            )}
          </View>
        ) : null}

        {model.photos.length > 0 ? (
          <View>
            <Text style={styles.sectionTitle}>Project Photos</Text>
            <View style={styles.photoGrid}>
              {model.photos.slice(0, 4).map((photo) => (
                // eslint-disable-next-line jsx-a11y/alt-text -- react-pdf Image
                <Image key={photo.id} src={photo.url} style={styles.photo} />
              ))}
            </View>
          </View>
        ) : null}

        <PageFooter proposalNumber={model.meta.proposalNumber ?? "Proposal"} />
      </Page>

      {model.lineItemTables.length > 0 ? (
        <Page size="LETTER" style={styles.page}>
          <Text style={{ fontFamily: "Helvetica-Bold", fontSize: 14, marginBottom: 12 }}>
            Line Item Breakdown
          </Text>
          {model.lineItemTables.map((table) => (
            <LineItemTable key={table.id} title={table.title} rows={table.rows} />
          ))}
          <PageFooter proposalNumber={model.meta.proposalNumber ?? "Proposal"} />
        </Page>
      ) : null}

      <Page size="LETTER" style={styles.page}>
        {legalSections.map((section) => (
          <Section key={section.id} title={section.title} body={section.body} />
        ))}

        {model.attachments.length > 0 ? (
          <View>
            <Text style={styles.sectionTitle}>Attachments</Text>
            {model.attachments.map((attachment) => (
              <View key={attachment.id} style={styles.attachmentRow}>
                <Link src={attachment.url}>
                  <Text>{attachment.title ?? attachment.fileName ?? attachment.url}</Text>
                </Link>
              </View>
            ))}
          </View>
        ) : null}

        <View style={styles.signatureRow}>
          <View style={styles.signatureBlock}>
            <Text style={styles.muted}>{model.signatures.customer.label}</Text>
            {model.signatures.customer.imageDataUrl ? (
              // eslint-disable-next-line jsx-a11y/alt-text -- react-pdf Image
              <Image
                src={model.signatures.customer.imageDataUrl}
                style={styles.signatureImage}
              />
            ) : null}
            <Text>{model.signatures.customer.name}</Text>
            {model.signatures.customer.title ? (
              <Text style={styles.muted}>{model.signatures.customer.title}</Text>
            ) : null}
            {model.signatures.customer.signedAtLabel ? (
              <Text style={styles.muted}>
                Signed {model.signatures.customer.signedAtLabel}
              </Text>
            ) : null}
          </View>
          <View style={styles.signatureBlock}>
            <Text style={styles.muted}>{model.signatures.contractor.label}</Text>
            <Text>{model.signatures.contractor.name}</Text>
            {model.signatures.contractor.title ? (
              <Text style={styles.muted}>{model.signatures.contractor.title}</Text>
            ) : null}
          </View>
        </View>

        <PageFooter proposalNumber={model.meta.proposalNumber ?? "Proposal"} />
      </Page>
    </Document>
  );
}
