import type { ProposalPortalData, ProposalWithRelations } from "@/lib/proposals/types";

export function mapPortalToPreviewProposal(
  portal: ProposalPortalData
): ProposalWithRelations {
  return {
    id: portal.id,
    title: portal.title,
    proposal_number: portal.proposal_number,
    proposal_date: portal.proposal_date,
    expiration_date: portal.expiration_date,
    amount: portal.amount,
    status: portal.status,
    project: {
      id: portal.project.id,
      project_name: portal.project.project_name,
      project_address: portal.project.project_address,
      project_type: portal.project.project_type,
      general_contractor: portal.project.general_contractor,
      bid_due_date: null,
      customer: {
        id: "portal-customer",
        company_name: portal.customer.company_name,
        contact_name: portal.customer.contact_name,
        email: portal.customer.email,
        phone_number: portal.customer.phone_number,
        project_address: portal.customer.project_address,
      },
    },
    estimate: null,
    estimate_snapshot: portal.estimate_snapshot,
    company_snapshot: portal.company_snapshot,
    sent_at: null,
    decided_at: portal.accepted_at ?? portal.declined_at,
    last_autosaved_at: null,
    created_at: portal.proposal_date,
    updated_at: portal.proposal_date,
    user_id: "portal",
    project_id: portal.project.id,
    estimate_id: null,
    scope_of_work: portal.scope_of_work,
    materials_summary: portal.materials_summary,
    labor_summary: portal.labor_summary,
    equipment_summary: portal.equipment_summary,
    show_line_item_breakdown: portal.show_line_item_breakdown,
    assumptions: portal.assumptions,
    exclusions: portal.exclusions,
    terms_and_conditions: portal.terms_and_conditions,
    warranty_information: portal.warranty_information,
    customer_signature_name: portal.customer_signature_name,
    customer_signature_title: portal.customer_signature_title,
    contractor_signature_name: portal.contractor_signature_name,
    contractor_signature_title: portal.contractor_signature_title,
    notes: portal.notes,
    internal_notes: null,
    public_token: null,
    viewed_at: null,
    first_viewed_at: null,
    accepted_at: portal.accepted_at,
    declined_at: portal.declined_at,
    archived_at: null,
    customer_signature_data: portal.customer_signature_data,
    customer_signed_at: portal.customer_signed_at,
    customer_signed_name: portal.customer_signed_name,
    customer_logo_url: portal.customer_logo_url,
    brand_primary_color: portal.brand_primary_color,
    brand_accent_color: portal.brand_accent_color,
    pdf_generated_at: null,
    pdf_page_count: null,
    last_emailed_at: null,
    email_send_count: 0,
  };
}

export function mapPortalToEditorState(portal: ProposalPortalData) {
  return {
    title: portal.title,
    proposal_date: portal.proposal_date?.slice(0, 10) ?? new Date().toISOString().slice(0, 10),
    expiration_date: portal.expiration_date?.slice(0, 10) ?? "",
    scope_of_work: portal.scope_of_work ?? "",
    materials_summary: portal.materials_summary ?? "",
    labor_summary: portal.labor_summary ?? "",
    equipment_summary: portal.equipment_summary ?? "",
    show_line_item_breakdown: portal.show_line_item_breakdown,
    assumptions: portal.assumptions ?? "",
    exclusions: portal.exclusions ?? "",
    terms_and_conditions: portal.terms_and_conditions ?? "",
    warranty_information: portal.warranty_information ?? "",
    customer_signature_name: portal.customer_signature_name ?? "",
    customer_signature_title: portal.customer_signature_title ?? "",
    contractor_signature_name: portal.contractor_signature_name ?? "",
    contractor_signature_title: portal.contractor_signature_title ?? "",
    notes: portal.notes ?? "",
    internal_notes: "",
  };
}
