import type { LineItemCatalog } from "@/lib/estimates/line-item-catalogs/types";
import { catalogItem } from "@/lib/estimates/line-item-catalogs/utils";

export const MATERIALS_CATALOG: LineItemCatalog = {
  category: "materials",
  label: "Materials",
  groups: [
    {
      id: "wire-cable",
      label: "Wire & cable",
      items: [
        catalogItem("Romex NM-B", "lf", ["romex", "nm-b", "14-2", "12-2"]),
        catalogItem("THHN Wire", "lf", ["thhn", "stranded"]),
        catalogItem("THWN Wire", "lf", ["thwn"]),
        catalogItem("MC Cable", "lf", ["mc", "metal clad"]),
        catalogItem("SER Cable", "lf", ["ser", "service entrance"]),
        catalogItem("UF Cable", "lf", ["uf", "underground"]),
        catalogItem("Low Voltage Cable", "lf", ["lv cable"]),
        catalogItem("CAT5e Cable", "lf", ["cat5e", "data"]),
        catalogItem("CAT6 Cable", "lf", ["cat6", "data"]),
        catalogItem("Coaxial Cable", "lf", ["coax"]),
      ],
    },
    {
      id: "conduit-fittings",
      label: "Conduit & fittings",
      items: [
        catalogItem("EMT Conduit", "lf", ["emt", "electrical metallic tubing"]),
        catalogItem("PVC Conduit", "lf", ["pvc"]),
        catalogItem("Rigid Metal Conduit", "lf", ["rmc", "rigid"]),
        catalogItem("Flexible Metal Conduit", "lf", ["fmc", "flex"]),
        catalogItem("Liquidtight Conduit", "lf", ["liquid tight", "sealtite"]),
        catalogItem("Conduit Coupling", "ea", ["coupling"]),
        catalogItem("Connector", "ea", ["conduit connector"]),
        catalogItem("Compression Connector", "ea", ["compression"]),
        catalogItem("Set Screw Connector", "ea", ["set screw"]),
        catalogItem("Bushing", "ea"),
        catalogItem("Locknut", "ea"),
        catalogItem("Conduit Strap", "ea", ["strap"]),
      ],
    },
    {
      id: "panels-breakers",
      label: "Panels & breakers",
      items: [
        catalogItem("Main Panel", "ea", ["service panel"]),
        catalogItem("Sub Panel", "ea", ["subpanel"]),
        catalogItem("Load Center", "ea"),
        catalogItem("Meter Base", "ea", ["meter socket"]),
        catalogItem("Main Breaker", "ea"),
        catalogItem("Single Pole Breaker", "ea", ["1p breaker"]),
        catalogItem("Double Pole Breaker", "ea", ["2p breaker"]),
        catalogItem("AFCI Breaker", "ea", ["afci", "arc fault"]),
        catalogItem("GFCI Breaker", "ea", ["gfci"]),
        catalogItem("Tandem Breaker", "ea", ["twin breaker"]),
      ],
    },
    {
      id: "devices",
      label: "Devices",
      items: [
        catalogItem("Duplex Outlet", "ea", ["receptacle", "outlet"]),
        catalogItem("GFCI Outlet", "ea", ["gfci receptacle"]),
        catalogItem("AFCI Outlet", "ea", ["afci receptacle"]),
        catalogItem("USB Outlet", "ea", ["usb receptacle"]),
        catalogItem("Smart Outlet", "ea", ["wifi outlet"]),
        catalogItem("Single Pole Switch", "ea", ["sp switch"]),
        catalogItem("Three-Way Switch", "ea", ["3-way"]),
        catalogItem("Four-Way Switch", "ea", ["4-way"]),
        catalogItem("Dimmer Switch", "ea", ["dimmer"]),
        catalogItem("Smart Switch", "ea", ["wifi switch"]),
      ],
    },
    {
      id: "boxes",
      label: "Boxes",
      items: [
        catalogItem("Plastic Device Box", "ea", ["plastic box"]),
        catalogItem("Metal Device Box", "ea", ["metal box"]),
        catalogItem("Junction Box", "ea", ["j-box"]),
        catalogItem("Ceiling Box", "ea", ["fan box"]),
        catalogItem("Weatherproof Box", "ea", ["wp box"]),
        catalogItem("Floor Box", "ea"),
      ],
    },
    {
      id: "lighting",
      label: "Lighting",
      items: [
        catalogItem("LED Recessed Light", "ea", ["can light", "downlight"]),
        catalogItem("LED Panel Light", "ea", ["panel"]),
        catalogItem("LED Strip Light", "ea", ["strip"]),
        catalogItem("High Bay Fixture", "ea", ["high bay"]),
        catalogItem("Wall Pack", "ea"),
        catalogItem("Flood Light", "ea", ["flood"]),
        catalogItem("Exit Sign", "ea"),
        catalogItem("Emergency Light", "ea", ["emergency"]),
      ],
    },
    {
      id: "safety-misc",
      label: "Safety & miscellaneous",
      items: [
        catalogItem("Wire Nuts", "ea", ["wirenut"]),
        catalogItem("Ground Rod", "ea"),
        catalogItem("Ground Clamp", "ea"),
        catalogItem("Electrical Tape", "ea", ["tape"]),
        catalogItem("Cable Staples", "ea", ["staples"]),
        catalogItem("Cable Ties", "ea", ["zip ties"]),
        catalogItem("Labels", "ea"),
        catalogItem("Screws", "ea"),
        catalogItem("Anchors", "ea"),
        catalogItem("Other / Custom", "ea", ["custom"]),
      ],
    },
  ],
};
