// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/ai" | "/analytics" | "/customers" | "/dashboard" | "/estimates" | "/estimates/[id]" | "/invite/[token]" | "/login" | "/p/[token]" | "/projects" | "/projects/[id]" | "/projects/[id]/edit" | "/projects/new" | "/proposals" | "/proposals/[id]" | "/settings" | "/settings/team"
type AppRouteHandlerRoutes = "/api/ai/estimate-assistant" | "/api/ai/estimate-review" | "/api/analytics/export/csv" | "/api/analytics/export/pdf" | "/api/proposals/portal/[token]" | "/api/search" | "/auth/callback" | "/p/[token]/pdf" | "/proposals/[id]/pdf"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/ai": {}
  "/analytics": {}
  "/api/ai/estimate-assistant": {}
  "/api/ai/estimate-review": {}
  "/api/analytics/export/csv": {}
  "/api/analytics/export/pdf": {}
  "/api/proposals/portal/[token]": { "token": string; }
  "/api/search": {}
  "/auth/callback": {}
  "/customers": {}
  "/dashboard": {}
  "/estimates": {}
  "/estimates/[id]": { "id": string; }
  "/invite/[token]": { "token": string; }
  "/login": {}
  "/p/[token]": { "token": string; }
  "/p/[token]/pdf": { "token": string; }
  "/projects": {}
  "/projects/[id]": { "id": string; }
  "/projects/[id]/edit": { "id": string; }
  "/projects/new": {}
  "/proposals": {}
  "/proposals/[id]": { "id": string; }
  "/proposals/[id]/pdf": { "id": string; }
  "/settings": {}
  "/settings/team": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
